# Generated by Django 5.2.7 on 2025-10-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_doc',
        ),
    ]
